//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// UploadFile
    /// </summary>
    [Serializable]
    public partial class UploadFile
    {
    public UploadFile()
        {
    	}
    			    /// <summary>
        /// 
        /// </summary>
        [MaxLength(450,ErrorMessage="最多只能输入450个字符")]
        [StringLength(450,ErrorMessage="最多只能输入450个字符")]
        [Key]
    
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string FileName { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string FilePath { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string Description { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string FileType { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public long FileSize { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string Extension { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public bool Enable { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public int SortCode { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public bool DeleteMark { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public System.Guid? CreateUserId { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string CreateUserName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.DateTime)]
    
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string Thumbnail { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string OwnTable { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string OwnId { get; set; }
    }
}
