//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    using System.ComponentModel.DataAnnotations;
    /// <summary>
    /// User
    /// </summary>
    [Serializable]
    public partial class User
    {
    public User()
        {
    	}
    			    /// <summary>
        /// 
        /// </summary>
        [MaxLength(450,ErrorMessage="最多只能输入450个字符")]
        [StringLength(450,ErrorMessage="最多只能输入450个字符")]
        [Key]
    
        public string Id { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string Account { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.Password)]
    
        public string Password { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string Name { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public int Sex { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public int Status { get; set; }
        /// <summary>
        /// 
        /// </summary>
        [DataType(DataType.DateTime)]
    
        public System.DateTime? CreateTime { get; set; }
        /// <summary>
        /// 
        /// </summary>
    
        public string CreateId { get; set; }
    }
}
