//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using Service;
using Model;

namespace WebAPI.Controllers
{
    public partial class MenuController: ApiController
		{
		 public MenuService menuService { get; set; }
        /// <summary>
        /// 新增
        /// </summary>
        /// <param name="menu"></param>
        /// <returns></returns>
		[HttpPost]
        public Result Add(Menu menu)
        {
            return menuService.Add(menu);
        }

        /// <summary>
        /// 修改
        /// </summary>
        /// <param name="menu"></param>
        /// <returns></returns>
		[HttpPost]
        public Result Update(Menu menu)
        {
            return menuService.Update(menu);
        }

        /// <summary>
        /// 删除
        /// </summary>
        /// <param name="menu"></param>
        /// <returns></returns>
		[HttpPost]
        public Result Delete(Menu menu)
        {
            return menuService.Delete(menu);
        }
		}
}
